#!/usr/bin/env python3
"""Download or prepare cached IAEA PRIS reactor enrichment files."""

from __future__ import annotations

import argparse
import csv
import re
import sys
import urllib.request
from html import unescape
from pathlib import Path

from russianinfra.power_enrichment_cache import cache_source_main


CACHE_DIR = Path("data/raw/power_enrichment/iaea_pris")
DEFAULT_RUSSIA_URL = "https://pris.iaea.org/PRIS/CountryStatistics/CountryDetails.aspx?current=RU"
DEFAULT_OUTPUT = "pris_russia_reactors.csv"
DEFAULT_USER_AGENT = "russianinfra-power-enrichment/0.8"
PRIS_FIELDS = [
    "reactor_name",
    "reactor_type",
    "status",
    "location",
    "reference_unit_power_mw",
    "gross_electrical_capacity_mw",
    "first_grid_connection",
    "station_name",
    "country",
    "source_url",
]


def fetch_text(url: str, timeout: int = 180) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": DEFAULT_USER_AGENT})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read().decode("utf-8", errors="replace")


def reactor_rows_from_country_page(html: str, source_url: str) -> list[dict[str, str]]:
    text = html_table_text(html)
    marker = "Name Type Status Location Reference Unit Power [MW] Gross Electrical Capacity [MW] First Grid Connection"
    if marker not in text:
        return []
    text = text.split(marker, 1)[1]
    text = re.split(r"Above data generated by the PRIS database\.|Copyright ©", text, maxsplit=1)[0]
    pattern = re.compile(
        r"(?P<name>[A-ZА-Я0-9][A-ZА-Я0-9 .'-]+?)\s+"
        r"(?P<type>PWR|BWR|FBR|LWGR|PHWR|GCR|HTGR|HWGCR|AGR)\s+"
        r"(?P<status>Operational|Under Construction|Permanent Shutdown|Suspended Operation)\s+"
        r"(?P<location>[A-ZА-Я][A-ZА-Я .'-]+?)\s+"
        r"(?P<reference>\d+(?:\.\d+)?)\s+"
        r"(?P<gross>\d+(?:\.\d+)?)"
        r"(?:\s+(?P<grid>\d{4}-\d{2}-\d{2}))?",
        re.I,
    )
    rows = []
    for match in pattern.finditer(text):
        reactor_name = " ".join(match.group("name").split())
        rows.append(
            {
                "reactor_name": reactor_name,
                "reactor_type": match.group("type").upper(),
                "status": normalize_pris_status(match.group("status")),
                "location": " ".join(match.group("location").split()).title(),
                "reference_unit_power_mw": match.group("reference"),
                "gross_electrical_capacity_mw": match.group("gross"),
                "first_grid_connection": match.group("grid") or "",
                "station_name": station_name_from_reactor(reactor_name),
                "country": "Russian Federation",
                "source_url": source_url,
            }
        )
    return rows


def html_table_text(html: str) -> str:
    text = re.sub(r"<script\b.*?</script>", " ", html, flags=re.I | re.S)
    text = re.sub(r"<style\b.*?</style>", " ", text, flags=re.I | re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    return " ".join(unescape(text).split())


def station_name_from_reactor(reactor_name: str) -> str:
    text = reactor_name.replace(" 2-", " 2-")
    text = re.sub(r"[-\s]+(?:unit\s*)?\d+$", "", text, flags=re.I)
    text = re.sub(r"\s+2-\d+$", " 2", text, flags=re.I)
    station = " ".join(text.split()).title()
    if "Nuclear" not in station and "Power" not in station:
        station = f"{station} Nuclear Power Plant"
    return station


def normalize_pris_status(raw: str) -> str:
    text = raw.casefold()
    if "under construction" in text:
        return "under_construction"
    if "shutdown" in text:
        return "shutdown"
    if "suspended" in text:
        return "suspended"
    if "operational" in text:
        return "operating"
    return "unknown"


def write_rows(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=PRIS_FIELDS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", action="append", type=Path, default=[], help="Local CSV or JSON file to copy into the PRIS cache.")
    parser.add_argument("--refresh", action="store_true", help="Download and parse the Russian Federation PRIS country page.")
    parser.add_argument("--url", default=DEFAULT_RUSSIA_URL, help="PRIS country details page URL.")
    parser.add_argument("--output-name", default=DEFAULT_OUTPUT, help="CSV filename for parsed PRIS reactor rows.")
    parser.add_argument("--timeout", type=int, default=180, help="Download timeout in seconds.")
    args = parser.parse_args(argv)

    if args.input:
        copy_args = []
        for path in args.input:
            copy_args.extend(["--input", str(path)])
        cache_source_main(CACHE_DIR, "IAEA PRIS", copy_args)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    if args.refresh:
        html = fetch_text(args.url, args.timeout)
        rows = reactor_rows_from_country_page(html, args.url)
        if not rows:
            raise RuntimeError(f"No PRIS reactor rows parsed from {args.url}")
        target = CACHE_DIR / args.output_name
        write_rows(target, rows)
        print(f"Downloaded {len(rows):,} IAEA PRIS reactor row(s) to {target}")
    elif not args.input:
        print(f"IAEA PRIS cache directory ready: {CACHE_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
